FROM node:22-bookworm-slim AS builder

WORKDIR /app

ARG NUXT_PUBLIC_API_BASE_URL_1=https://api.ui.ac.id
ARG NUXT_PUBLIC_API_BASE_URL_2=/api
ARG NUXT_PUBLIC_AUTH_ENABLED=true
ARG NUXT_PUBLIC_MOCK_UI_API_ENABLED=false
ARG NUXT_PUBLIC_DEV_USERNAME=local_admin
ARG NUXT_PUBLIC_DEV_DISPLAY_NAME="Local Admin"
ARG NUXT_PUBLIC_DEV_USER_ROLE=admin
ARG NUXT_PUBLIC_DEV_USER_CIVITAS=staf

ENV NUXT_PUBLIC_API_BASE_URL_1=${NUXT_PUBLIC_API_BASE_URL_1}
ENV NUXT_PUBLIC_API_BASE_URL_2=${NUXT_PUBLIC_API_BASE_URL_2}
ENV NUXT_PUBLIC_AUTH_ENABLED=${NUXT_PUBLIC_AUTH_ENABLED}
ENV NUXT_PUBLIC_MOCK_UI_API_ENABLED=${NUXT_PUBLIC_MOCK_UI_API_ENABLED}
ENV NUXT_PUBLIC_DEV_USERNAME=${NUXT_PUBLIC_DEV_USERNAME}
ENV NUXT_PUBLIC_DEV_DISPLAY_NAME=${NUXT_PUBLIC_DEV_DISPLAY_NAME}
ENV NUXT_PUBLIC_DEV_USER_ROLE=${NUXT_PUBLIC_DEV_USER_ROLE}
ENV NUXT_PUBLIC_DEV_USER_CIVITAS=${NUXT_PUBLIC_DEV_USER_CIVITAS}

RUN corepack enable && corepack prepare pnpm@10.33.0 --activate

COPY package.json pnpm-lock.yaml .npmrc ./
RUN pnpm install --frozen-lockfile --ignore-scripts

COPY . .
RUN pnpm generate

FROM nginx:1.27-alpine AS runner

COPY docker/nginx-spa.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/.output/public /usr/share/nginx/html

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]
