// Server-side applications DB. This file mirrors `data/applications.ts` but
// uses static public image paths for logos so it can be serialized by the server.

import { readJson, writeJson } from '@/server/fake-db/persistence'

// Prefer public/ assets for stable paths in production builds
const LogoUIPath = getPublicUrl('/images/beranda/logo-UI.png')

const defaultDb = {
  studentApplications: [
    {
      name: 'Sistem Informasi Akademik UI',
      nameShort: 'SIAK',
      faculty: 'UI',
      link: 'https://academic.ui.ac.id/',
      logo: LogoUIPath,
    },
    {
      name: 'Platform e-learning UI',
      nameShort: 'Emas',
      faculty: 'UI',
      link: 'https://emas2.ui.ac.id/',
      logo: '',
    },
    {
      name: 'Layanan kemahasiswaan UI',
      nameShort: 'Kemahasiswaan',
      faculty: 'UI',
      link: 'https://kemahasiswaan.ui.ac.id/',
      logo: '',
    },
    {
      name: 'Website perpustakaan UI',
      nameShort: 'Lib',
      faculty: 'UI',
      link: 'https://lib.ui.ac.id/',
      logo: '',
    },
    {
      name: 'Center of Independent Learning',
      nameShort: 'CIL',
      faculty: 'UI',
      link: 'https://cil.ui.ac.id/',
      logo: '',
    },
    {
      name: 'Informasi Beasiswa',
      nameShort: 'Beasiswa',
      faculty: 'UI',
      link: 'http://beasiswa.ui.ac.id/',
      logo: '',
    },
    {
      name: 'Peminjaman Fasilitas Kampus',
      nameShort: 'SIJAFAS',
      faculty: 'UI',
      link: 'https://dopf.ui.ac.id/peminjaman/',
      logo: LogoUIPath,
    },
    {
      name: 'Aduan Fasilitas',
      nameShort: 'SIPAF',
      faculty: 'UI',
      link: 'https://dppf.ui.ac.id/sipaf/',
      logo: '',
    },
    {
      name: 'Parkir UI',
      nameShort: 'Parkir',
      faculty: 'UI',
      link: 'https://parkir.ui.ac.id/',
      logo: '',
    },
    {
      name: 'Manajemen Aset',
      nameShort: 'SIMAF',
      faculty: 'UI',
      link: 'https://simaf.ui.ac.id/',
      logo: LogoUIPath,
    },
    {
      name: 'Operasi & Pemeliharaan Fasilitas',
      nameShort: 'DOPFMA',
      faculty: 'UI',
      link: 'https://dopf.ui.ac.id/v1/',
      logo: LogoUIPath,
    },
    {
      name: 'Webmail UI',
      nameShort: 'Webmail',
      faculty: 'UI',
      link: 'https://webmail.ui.ac.id/admin/',
      logo: '',
    },
    {
      name: 'International UI',
      nameShort: 'International UI',
      faculty: 'UI',
      link: 'https://international.ui.ac.id/',
      logo: LogoUIPath,
    },
    {
      name: 'Layanan Bahasa UI',
      nameShort: 'LBI',
      faculty: 'UI',
      link: 'https://lbifib.ui.ac.id/',
      logo: '',
    },
    {
      name: 'E-learning Fasilkom',
      nameShort: 'SceLe',
      faculty: 'Fasilkom',
      link: 'https://scele.cs.ui.ac.id/',
      logo: LogoUIPath,
    },
    {
      name: 'Request Surat Fasilkom',
      nameShort: 'Sisurat',
      faculty: 'Fasilkom',
      link: 'https://surat.cs.ui.ac.id/',
      logo: '',
    },
    {
      name: 'Asisten Dosen Fasilkom',
      nameShort: 'Siasisten',
      faculty: 'Fasilkom',
      link: 'https://siasisten.cs.ui.ac.id/',
      logo: '',
    },
    {
      name: 'Platform Assignment Fasilkom',
      nameShort: 'Aren',
      faculty: 'Fasilkom',
      link: 'https://aren.cs.ui.ac.id/',
      logo: LogoUIPath,
    },
    {
      name: 'Melihat bangku & ruangan ujian Fasilkom',
      nameShort: 'Sibangku',
      faculty: 'Fasilkom',
      link: 'https://ujian.cs.ui.ac.id/sibangku/',
      logo: '',
    },
    {
      name: 'Website perpustakaan Fasilkom',
      nameShort: 'Lontar',
      faculty: 'Fasilkom',
      link: 'https://lontar.cs.ui.ac.id/',
      logo: LogoUIPath,
    },
    {
      name: 'Request surat/dokumen',
      nameShort: 'Pemirsa',
      faculty: 'FKM',
      link: 'https://surat.fkm.ui.ac.id/',
      logo: '',
    },
    {
      name: 'Peminjaman ruangan FKM',
      nameShort: 'SIM',
      faculty: 'FKM',
      link: 'https://sim.fkm.ui.ac.id/',
      logo: LogoUIPath,
    },
    {
      name: 'Sistem Informasi Kinerja FKM',
      nameShort: 'SISKA',
      faculty: 'FKM',
      link: 'https://sisfo.fkm.ui.ac.id/siska/',
      logo: LogoUIPath,
    },
    {
      name: 'Kaji Etik FKM',
      nameShort: 'Kajietik',
      faculty: 'FKM',
      link: 'https://kajietik.fkm.ui.ac.id/',
      logo: '',
    },
    {
      name: 'E-Komplain FKM UI',
      nameShort: 'E-komplain',
      faculty: 'FKM',
      link: 'https://komplain.fkm.ui.ac.id',
      logo: '',
    },
    {
      name: 'Sistem Informasi Dokumentasi Ujian',
      nameShort: 'SIDU',
      faculty: 'FKM',
      link: 'https://sim.fkm.ui.ac.id/sidu/',
      logo: LogoUIPath,
    },
    {
      name: 'Aplikasi Disposisi FKM',
      nameShort: 'DISPOSISI',
      faculty: 'FKM',
      link: 'https://sim.fkm.ui.ac.id/disposisi/',
      logo: '',
    },
    {
      name: 'Aplikasi Ujian Mandiri',
      nameShort: 'UM',
      faculty: 'FKM',
      link: 'https://sim.fkm.ui.ac.id/um/gerbang/index.php',
      logo: LogoUIPath,
    },
    {
      name: 'Sistem Informasi Riset Akademik Kerjasama',
      nameShort: 'SIRAJA',
      faculty: 'FKM',
      link: 'https://sim.fkm.ui.ac.id/siraja/',
      logo: '',
    },
    {
      name: 'Sistem Informasi FKM',
      nameShort: 'SISFO',
      faculty: 'FKM',
      link: 'https://sisfo.fkm.ui.ac.id/',
      logo: LogoUIPath,
    },
    {
      name: 'Portal aplikasi resmi FPsi',
      nameShort: 'Portal FPsi',
      faculty: 'FPsi',
      link: 'https://portal-psikoui.com/',
      logo: '',
    },
    {
      name: 'Pusat Sumber Belajar FEB',
      nameShort: 'PSB',
      faculty: 'FEB',
      link: 'https://psb.feb.ui.ac.id/',
      logo: '',
    },
    {
      name: 'Sistem Informasi Layanan Penggunaan Ruang',
      nameShort: 'SIMAYANG',
      faculty: 'FEB',
      link: 'https://app.feb.ui.ac.id/simayang/',
      logo: '',
    },
    {
      name: 'Sistem informasi Prodi Ilmu Komunikasi',
      nameShort: 'PSDK',
      faculty: 'FISIP',
      link: 'https://psdk.ui.ac.id/',
      logo: '',
    },
  ],

  dosenApplications: [
    {
      name: 'Sistem Informasi Akademik Next Generation (SIAK NG)',
      nameShort: 'SIAK-NG',
      faculty: 'UI',
      link: 'https://academic.ui.ac.id/',
      logo: '',
    },
    {
      name: 'Aplikasi Naskah Dinas Elektronik Universitas Indonesia',
      nameShort: 'ANDIENI',
      faculty: 'UI',
      link: 'https://andieni.ui.ac.id/',
      logo: LogoUIPath,
    },
    {
      name: 'Arsip Akademik dan Ijazah (Arsemik)',
      nameShort: 'ARSEMIK',
      faculty: 'UI',
      link: 'https://arsemik.ui.ac.id/',
      logo: '',
    },
    {
      name: 'Sistem Informasi Layanan Asrama UI',
      nameShort: 'Asrama',
      faculty: 'UI',
      link: 'https://asrama.ui.ac.id/',
      logo: LogoUIPath,
    },
    {
      name: 'Sistem Informasi Administarasi Sekolah UI (SKSG / SIL)',
      nameShort: 'BAS',
      faculty: 'UI',
      link: 'https://bas.ui.ac.id/',
      logo: LogoUIPath,
    },
    {
      name: 'Sistem Informasi Biaya Pendidikan',
      nameShort: 'BP',
      faculty: 'UI',
      link: 'https://bp.ui.ac.id/',
      logo: LogoUIPath,
    },
    {
      name: 'Administrasi pengelolaan seminar internasional (pendaftaran sampai dengan pelaksanaan)',
      nameShort: 'Conference UI',
      faculty: 'UI',
      link: 'https://conference.ui.ac.id/',
      logo: '',
    },
    {
      name: 'Sistem Peminjaman Fasilitas (SIJAFAS)',
      nameShort: 'SIJAFAS',
      faculty: 'UI',
      link: 'https://dopf.ui.ac.id/peminjaman/',
      logo: '',
    },
    {
      name: 'Sistem Informasi Perawatan Aset dan Fasilitas (SIPAF)',
      nameShort: 'SIPAF',
      faculty: 'UI',
      link: 'https://dppf.ui.ac.id/sipaf/',
      logo: '',
    },
    {
      name: 'Sistem manajemen file untuk menyimpan file kerja staf UI',
      nameShort: 'Files UI',
      faculty: 'UI',
      link: 'https://files.ui.ac.id/',
      logo: LogoUIPath,
    },
    {
      name: 'Sistem yang digunakan untuk mengelola data penelitian, pengabdian masyarakat, inovasi dan inkubasi.',
      nameShort: 'Grant Management',
      faculty: 'UI',
      link: 'https://grant.ui.ac.id/',
      logo: LogoUIPath,
    },
    {
      name: 'Portal Informasi Green Metric',
      nameShort: 'GreenMetric',
      faculty: 'UI',
      link: 'https://greenmetric.ui.ac.id/',
      logo: '',
    },
    {
      name: 'Human Resource Information System (HRIS)',
      nameShort: 'HRIS',
      faculty: 'UI',
      link: 'https://hris.ui.ac.id/',
      logo: '',
    },
    {
      name: 'Sistem Informasi Knowledge Management (SIKM)',
      nameShort: 'Kelola',
      faculty: 'UI',
      link: 'https://kelola.ui.ac.id/',
      logo: '',
    },
    {
      name: 'Library Automation and Digital Archive (LONTAR)',
      nameShort: 'LONTAR',
      faculty: 'UI',
      link: 'https://lib.ui.ac.id/',
      logo: '',
    },
    {
      name: 'Unggah Karya Ilmiah (UIANA)',
      nameShort: 'UIANA',
      faculty: 'UI',
      link: 'https://lib.ui.ac.id/unggah/',
      logo: '',
    },
    {
      name: 'Sistem Layanan Pengadaan Secara Elektronik (SLPSE)',
      nameShort: 'LPSE',
      faculty: 'UI',
      link: 'https://lpse.ui.ac.id/',
      logo: '',
    },
    {
      name: 'Cloud platform: aplikasi Office, OneDrive, Outlook',
      nameShort: 'Office365',
      faculty: 'UI',
      link: 'https://office365.ui.ac.id/',
      logo: '',
    },
    {
      name: 'Oracle Finance (Orafin)',
      nameShort: 'Orafin',
      faculty: 'UI',
      link: 'https://orafin-app.ui.ac.id:8000/',
      logo: '',
    },
    {
      name: 'Pencatatan dan pelaporan parkir kendaraan di lingkungan Universitas Indonesia',
      nameShort: 'Parkir UI',
      faculty: 'UI',
      link: 'https://parkir.ui.ac.id/',
      logo: '',
    },
    {
      name: 'Portal Informasi Pengajuan Izin Kegiatan melalui Unit Pelayanan Teknis Pengamanan Lingkungan kampus',
      nameShort: 'PLK',
      faculty: 'UI',
      link: 'https://plk.ui.ac.id/',
      logo: '',
    },
    {
      name: 'Aplikasi Jurnal Online UI',
      nameShort: 'Remote Lib UI',
      faculty: 'UI',
      link: 'https://remote-lib.ui.ac.id/',
      logo: '',
    },
    {
      name: 'Sistem Arsip Dokumen UI',
      nameShort: 'Repository UI',
      faculty: 'UI',
      link: 'https://repository.ui.ac.id/',
      logo: '',
    },
    {
      name: 'Monitoring publikasi peneliti UI berdasarkan scopus',
      nameShort: 'Scholar UI',
      faculty: 'UI',
      link: 'https://scholar.ui.ac.id/',
      logo: '',
    },
    {
      name: 'Sistem Elektronik Kearsipan (SEKAR)',
      nameShort: 'SEKAR UI',
      faculty: 'UI',
      link: 'https://sekar.ui.ac.id/',
      logo: '',
    },
    {
      name: 'Sistem Informasi Aset dan Fasilitas (SIMAF)',
      nameShort: 'SIMAF',
      faculty: 'UI',
      link: 'https://simaf.ui.ac.id/',
      logo: '',
    },
    {
      name: 'Sistem Informasi Kepegawaian (SIPEG)',
      nameShort: 'SIPEG',
      faculty: 'UI',
      link: 'https://sipeg.ui.ac.id/',
      logo: '',
    },
    {
      name: 'Sistem Informasi Penjaminan Mutu Akademik (SIPMA)',
      nameShort: 'SIPMA',
      faculty: 'UI',
      link: 'https://sipma.ui.ac.id/',
      logo: '',
    },
    {
      name: 'Sistem Informasi Rencana Umum Pengadaan (SIRUP)',
      nameShort: 'SIRUP',
      faculty: 'UI',
      link: 'https://sirup.ui.ac.id/',
      logo: '',
    },
    {
      name: 'Sistem Informasi Perpajakan UI',
      nameShort: 'Si-Pajak',
      faculty: 'UI',
      link: 'https://tax.ui.ac.id/',
      logo: '',
    },
    {
      name: 'Portal Informasi seputar UI dan dinamikanya',
      nameShort: 'UI ac id',
      faculty: 'UI',
      link: 'https://ui.ac.id/',
      logo: '',
    },
    {
      name: 'Transfer file tools UI',
      nameShort: 'Upload UI',
      faculty: 'UI',
      link: 'https://upload.ui.ac.id/',
      logo: '',
    },
    {
      name: 'Vendor Management System (VMS) merupakan tempat pendaftaran penyedia untuk pengadaan barang dan jasa',
      nameShort: 'Vendor Management',
      faculty: 'UI',
      link: 'https://vms.ui.ac.id/',
      logo: '',
    },
    {
      name: 'Layanan surel UI',
      nameShort: 'Webmail',
      faculty: 'UI',
      link: 'https://webmail.ui.ac.id/',
      logo: '',
    },
  ],

  stafApplications: [
    {
      name: 'Sistem Informasi Akademik Next Generation (SIAK NG)',
      nameShort: 'SIAK-NG',
      faculty: 'UI',
      link: 'https://academic.ui.ac.id/',
      logo: '',

      nameShort: 'ANDIENI',
      faculty: 'UI',
      link: 'https://andieni.ui.ac.id/',
      logo: LogoUIPath,
    },
    {
      name: 'Arsip Akademik dan Ijazah (Arsemik)',
      nameShort: 'ARSEMIK',
      faculty: 'UI',
      link: 'https://arsemik.ui.ac.id/',
      logo: '',
    },
    {
      name: 'Sistem Informasi Layanan Asrama UI',
      nameShort: 'Asrama',
      faculty: 'UI',
      link: 'https://asrama.ui.ac.id/',
      logo: LogoUIPath,
    },
    {
      name: 'Sistem Informasi Administarasi Sekolah UI (SKSG / SIL)',
      nameShort: 'BAS',
      faculty: 'UI',
      link: 'https://bas.ui.ac.id/',
      logo: LogoUIPath,
    },
    {
      name: 'Sistem Informasi Biaya Pendidikan',
      nameShort: 'BP',
      faculty: 'UI',
      link: 'https://bp.ui.ac.id/',
      logo: LogoUIPath,
    },
    {
      name: 'Administrasi pengelolaan seminar internasional (pendaftaran sampai dengan pelaksanaan)',
      nameShort: 'Conference UI',
      faculty: 'UI',
      link: 'https://conference.ui.ac.id/',
      logo: '',
    },
    {
      name: 'Sistem Peminjaman Fasilitas (SIJAFAS)',
      nameShort: 'SIJAFAS',
      faculty: 'UI',
      link: 'https://dopf.ui.ac.id/peminjaman/',
      logo: '',
    },
    {
      name: 'Sistem Informasi Perawatan Aset dan Fasilitas (SIPAF)',
      nameShort: 'SIPAF',
      faculty: 'UI',
      link: 'https://dppf.ui.ac.id/sipaf/',
      logo: '',
    },
    {
      name: 'Sistem manajemen file untuk menyimpan file kerja staf UI',
      nameShort: 'Files UI',
      faculty: 'UI',
      link: 'https://files.ui.ac.id/',
      logo: LogoUIPath,
    },
    {
      name: 'Sistem yang digunakan untuk mengelola data penelitian, pengabdian masyarakat, inovasi dan inkubasi.',
      nameShort: 'Grant Management',
      faculty: 'UI',
      link: 'https://grant.ui.ac.id/',
      logo: LogoUIPath,
    },
    {
      name: 'Portal Informasi Green Metric',
      nameShort: 'GreenMetric',
      faculty: 'UI',
      link: 'https://greenmetric.ui.ac.id/',
      logo: '',
    },
    {
      name: 'Human Resource Information System (HRIS)',
      nameShort: 'HRIS',
      faculty: 'UI',
      link: 'https://hris.ui.ac.id/',
      logo: '',
    },
    {
      name: 'Sistem Informasi Knowledge Management (SIKM)',
      nameShort: 'Kelola',
      faculty: 'UI',
      link: 'https://kelola.ui.ac.id/',
      logo: '',
    },
    {
      name: 'Library Automation and Digital Archive (LONTAR)',
      nameShort: 'LONTAR',
      faculty: 'UI',
      link: 'https://lib.ui.ac.id/',
      logo: '',
    },
    {
      name: 'Unggah Karya Ilmiah (UIANA)',
      nameShort: 'UIANA',
      faculty: 'UI',
      link: 'https://lib.ui.ac.id/unggah/',
      logo: '',
    },
    {
      name: 'Sistem Layanan Pengadaan Secara Elektronik (SLPSE)',
      nameShort: 'LPSE',
      faculty: 'UI',
      link: 'https://lpse.ui.ac.id/',
      logo: '',
    },
    {
      name: 'Cloud platform: aplikasi Office, OneDrive, Outlook',
      nameShort: 'Office365',
      faculty: 'UI',
      link: 'https://office365.ui.ac.id/',
      logo: '',
    },
    {
      name: 'Oracle Finance (Orafin)',
      nameShort: 'Orafin',
      faculty: 'UI',
      link: 'https://orafin-app.ui.ac.id:8000/',
      logo: '',
    },
    {
      name: 'Pencatatan dan pelaporan parkir kendaraan di lingkungan Universitas Indonesia',
      nameShort: 'Parkir UI',
      faculty: 'UI',
      link: 'https://parkir.ui.ac.id/',
      logo: '',
    },
    {
      name: 'Portal Informasi Pengajuan Izin Kegiatan melalui Unit Pelayanan Teknis Pengamanan Lingkungan kampus',
      nameShort: 'PLK',
      faculty: 'UI',
      link: 'https://plk.ui.ac.id/',
      logo: '',
    },
    {
      name: 'Aplikasi Jurnal Online UI',
      nameShort: 'Remote Lib UI',
      faculty: 'UI',
      link: 'https://remote-lib.ui.ac.id/',
      logo: '',
    },
    {
      name: 'Sistem Arsip Dokumen UI',
      nameShort: 'Repository UI',
      faculty: 'UI',
      link: 'https://repository.ui.ac.id/',
      logo: '',
    },
    {
      name: 'Monitoring publikasi peneliti UI berdasarkan scopus',
      nameShort: 'Scholar UI',
      faculty: 'UI',
      link: 'https://scholar.ui.ac.id/',
      logo: '',
    },
    {
      name: 'Sistem Elektronik Kearsipan (SEKAR)',
      nameShort: 'SEKAR UI',
      faculty: 'UI',
      link: 'https://sekar.ui.ac.id/',
      logo: '',
    },
    {
      name: 'Sistem Informasi Aset dan Fasilitas (SIMAF)',
      nameShort: 'SIMAF',
      faculty: 'UI',
      link: 'https://simaf.ui.ac.id/',
      logo: '',
    },
    {
      name: 'Sistem Informasi Kepegawaian (SIPEG)',
      nameShort: 'SIPEG',
      faculty: 'UI',
      link: 'https://sipeg.ui.ac.id/',
      logo: '',
    },
    {
      name: 'Sistem Informasi Penjaminan Mutu Akademik (SIPMA)',
      nameShort: 'SIPMA',
      faculty: 'UI',
      link: 'https://sipma.ui.ac.id/',
      logo: '',
    },
    {
      name: 'Sistem Informasi Rencana Umum Pengadaan (SIRUP)',
      nameShort: 'SIRUP',
      faculty: 'UI',
      link: 'https://sirup.ui.ac.id/',
      logo: '',
    },
    {
      name: 'Sistem Informasi Perpajakan UI',
      nameShort: 'Si-Pajak',
      faculty: 'UI',
      link: 'https://tax.ui.ac.id/',
      logo: '',
    },
    {
      name: 'Portal Informasi seputar UI dan dinamikanya',
      nameShort: 'UI ac id',
      faculty: 'UI',
      link: 'https://ui.ac.id/',
      logo: '',
    },
    {
      name: 'Transfer file tools UI',
      nameShort: 'Upload UI',
      faculty: 'UI',
      link: 'https://upload.ui.ac.id/',
      logo: '',
    },
    {
      name: 'Vendor Management System (VMS) merupakan tempat pendaftaran penyedia untuk pengadaan barang dan jasa',
      nameShort: 'Vendor Management',
      faculty: 'UI',
      link: 'https://vms.ui.ac.id/',
      logo: '',
    },
    {
      name: 'Layanan surel UI',
      nameShort: 'Webmail',
      faculty: 'UI',
      link: 'https://webmail.ui.ac.id/',
      logo: '',
    },
  ],
}

export const db = readJson('applications.json', defaultDb) as any

export function saveApplications() {
  return writeJson('applications.json', db)
}

export interface AppItem {
  name: string
  nameShort: string
  faculty: string
  link: string
  logo?: string
}

export default db
