name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Apply Kubernetes
        working-directory: k8s
        run: |
          export KUBECONFIG=kubeconfig.yaml
          kubectl apply -f deployment.yaml
