name: Docker

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login Docker Hub
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build image
        run: |
          TAG="${GITHUB_SHA}-$(date +%Y%m%d-%H%M%S)"

          docker build . \
            -t wisnunugroho13/civitas:$TAG \
            -t wisnunugroho13/civitas:latest

          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Push image
        run: |
          docker push wisnunugroho13/civitas:$TAG
          docker push wisnunugroho13/civitas:latest
